# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "out"
solc = "0.8.24"
src = "src"
test = "test"
remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/',
  '@safecall=lib/ExcessivelySafeCall/src/',
  '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
  '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol/'
]

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 4
